require('core.options')
require('core.autocmds')
require('core.keymaps')
require('core.colors')

require('plugins.colorscheme')
require('plugins.nvim-tree')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.gitsigns')

require('plugins.lualine')
require('plugins.cmp')
require('plugins.formatting')
require('plugins.todo')
require('plugins.gitsigns')
require('plugins.mini')
require('plugins.which-key')
