# #######################################################################################
# AUTOSTART — Programs launched on Hyprland start
# https://wiki.hypr.land/Configuring/Keywords/#executing
# #######################################################################################

exec-once = waybar & firefox
exec-once = systemctl --user start hyprpolkitagent
exec-once = udiskie
exec-once = hypridle
